version: 0.2
env:
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
phases:
  install:
    commands:
      - |
        if [ -f .copilot/phases/install.sh ]; then 
          bash .copilot/phases/install.sh; 
        fi
  pre_build:
    commands:
      - |
        if [ -f .copilot/phases/pre_build.sh ]; then 
          bash .copilot/phases/pre_build.sh; 
        fi
  build:
    commands:
      - codebuild-breakpoint
      - |
        if [ -f .copilot/phases/build.sh ]; then 
          bash .copilot/phases/build.sh; 
        fi
  post_build:
    commands:
      - |
        if [ -f .copilot/phases/post_build.sh ]; then 
          bash .copilot/phases/post_build.sh; 
        fi
