services:
  nginx:
    image: public.ecr.aws/uktrade/nginx-reverse-proxy:latest
    ports:
      - "9999:443"
    environment:
      SERVER: ipfilter:8000
  ipfilter:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      COPILOT_APPLICATION_NAME: localtest
      COPILOT_ENVIRONMENT_NAME: dev
      EMAIL_NAME: 'The Department for International Trade WebOps team'
      EMAIL: test@test.test
      LOG_LEVEL: INFO
      SERVER: host.docker.internal:8080
      #SENTRY_DSN: https://.... 
      ADDITIONAL_IP_LIST: 1.1.1.1
      IP_DETERMINED_BY_X_FORWARDED_FOR_INDEX: -2
  app:
    image: nginx:latest
    ports:
      - "8080:80"
