version: 0.2

env:
    variables:
      ECR_VISIBILITY: PUBLIC

phases:
  pre_build:
    commands:
      - pwd
      - ls -al

  build:
    commands:
      - echo "BUILD WOULD HAPPEN NOW"
      # - /work/build.sh
